### ISSUE TITLE
cannot find -lboost_python2.7

### ISSUE THREAD

**Issue by karshtharyani** [cfinch/Shocksolution_Examples#4]
I am getting the following error while building the shared library
```
g++ -shared -Wl,--export-dynamic hello_ext.o -L/usr/lib -lboost_python-2.7 -L/usr/lib/python2.7/config -lpython2.7 -o hello_ext.so
/usr/bin/ld: cannot find -lboost_python-2.7
collect2: error: ld returned 1 exit status
makefile:15: recipe for target 'hello_ext.so' failed
make: *** [hello_ext.so] Error 1
```

**Comment by craigafinch** [comment]
@karshtharyani The library linking command is highly dependent upon the configuration of your particular system. The linker can't find the Boost.Python library for Python 2.7 on your system, and that's all I can tell from the error message. Please make sure that you have Python 2.7, the appropriate Boost.Python library is installed and compiled on your system, and the linker is configured with the path to the Boost.Python library.

**Comment by karshtharyani** [comment]
@craigafinch As you correctly pointed out, it was a linker error. I had to make some edits in the makefile. Here is a modified version of the same

```
  1 # location of the Python header files
  2 
  3 PYTHON_VERSION = 2.7
  4 PYTHON_INCLUDE = /usr/include/python$(PYTHON_VERSION)
  5 
  6 # location of the Boost Python include files and library
  7 
  8 BOOST_INC = /usr/include/x86_64-linux-gnu
  9 BOOST_LIB = /usr/lib/x86_64-linux-gnu
 10 # compile mesh classes
 11 TARGET = hello_ext
 12 
 13 $(TARGET).so: $(TARGET).o
 14     g++ -shared -Wl,--export-dynamic $(TARGET).o -L$(BOOST_LIB) -lboost_python-py27 -L/usr/lib/python$(PYTHON_VERSION)/config -lpython$(PYTHON_VERSION) -o $(TARGET).so
 15 
 16 $(TARGET).o: $(TARGET).C
 17     g++ -I$(PYTHON_INCLUDE) -I$(BOOST_INC) -fPIC -c $(TARGET).C
 18 
 19 clean:
 20     rm -rf *.o *.so
```
The modification is on line 14. I changed it to `-lboost_python-py27` instead of `-lboost_python-python2.7`.
Additionally, I had to change lines 8 and 9 to locate the boost_libraries.

Thanks for responding.
